In [27]:
from google.colab import drive
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
project_directory = '/content/drive/MyDrive/Analytic Tools/'

In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

## Importing the Crime_Data_from_2010_to_2019.csv Dataset

In [30]:
df = pd.read_csv(project_directory+'/Crime_Data_from_2010_to_2019.csv')

In [31]:
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,08/09/2010 12:00:00 AM,08/09/2010 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,01/05/2010 12:00:00 AM,01/05/2010 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,01/03/2010 12:00:00 AM,01/02/2010 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2119792,190506304,02/22/2019 12:00:00 AM,02/22/2019 12:00:00 AM,840,5,Harbor,569,2,627,CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT,...,AO,Adult Other,627.0,NaN,NaN,NaN,100 W 22ND ST,NaN,33.7257,-118.2801
2119793,190608903,03/28/2019 12:00:00 AM,03/28/2019 12:00:00 AM,400,6,Hollywood,644,1,648,ARSON,...,IC,Invest Cont,648.0,NaN,NaN,NaN,1400 N LA BREA AV,NaN,34.0962,-118.3490
2119794,192004409,01/06/2019 12:00:00 AM,01/06/2019 12:00:00 AM,2100,20,Olympic,2029,2,930,CRIMINAL THREATS - NO WEAPON DISPLAYED,...,IC,Invest Cont,930.0,NaN,NaN,NaN,6TH,VIRGIL,34.0637,-118.2870
2119795,191716777,10/17/2019 12:00:00 AM,10/16/2019 12:00:00 AM,1800,17,Devonshire,1795,1,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),...,IC,Invest Cont,420.0,NaN,NaN,NaN,17200 NAPA ST,NaN,34.2266,-118.5085
2119796,190805435,02/01/2019 12:00:00 AM,02/01/2019 12:00:00 AM,1615,8,West LA,852,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,NaN,NaN,NaN,1700 BARRY AV,NaN,34.0420,-118.4531

In [32]:
df.nunique()

DR_NO             2119797
Date Rptd            4497
DATE OCC             3652
TIME OCC             1439
AREA                   21
AREA NAME              21
Rpt Dist No          1303
Part 1-2                2
Crm Cd                142
Crm Cd Desc           142
Mocodes            486164
Vict Age              112
Vict Sex                6
Vict Descent           20
Premis Cd             325
Premis Desc           320
Weapon Used Cd         80
Weapon Desc            79
Status                  9
Status Desc             6
Crm Cd 1              148
Crm Cd 2              143
Crm Cd 3               63
Crm Cd 4               12
LOCATION            75540
Cross Street        12878
LAT                  5437
LON                  5097
dtype: int64

In [33]:
df.rename(columns={'Crm Cd Desc': 'Crm_Cd_Desc'}, inplace=True)

In [34]:
df.Crm_Cd_Desc.unique()

array(['VIOLATION OF COURT ORDER',
       'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
       'OTHER MISCELLANEOUS CRIME', 'RAPE, ATTEMPTED',
       'SHOPLIFTING - PETTY THEFT ($950 & UNDER)',
       'BURGLARY FROM VEHICLE',
       'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
       'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
       'BATTERY - SIMPLE ASSAULT', 'ROBBERY', 'BOMB SCARE',
       'CHILD NEGLECT (SEE 300 W.I.C.)',
       'INTIMATE PARTNER - AGGRAVATED ASSAULT',
       'INTIMATE PARTNER - SIMPLE ASSAULT',
       'THEFT PLAIN - PETTY ($950 & UNDER)',
       'CRIMINAL THREATS - NO WEAPON DISPLAYED', 'ATTEMPTED ROBBERY',
       'VANDALISM - MISDEAMEANOR ($399 OR UNDER)', 'BURGLARY', 'ARSON',
       'RAPE, FORCIBLE', 'BRANDISH WEAPON',
       'THROWING OBJECT AT MOVING VEHICLE',
       'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
       'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
       'SHOTS FIRED AT INHABITED DWELLING', 'VEHICLE - STOLEN',
       'KIDNAPPING - GRAND ATTEMPT', 'CRIMINAL HOMICIDE',
       'THEFT PLAIN - ATTEMPT', 'THEFT, PERSON', 'TRESPASSING',
       'KIDNAPPING', 'VEHICLE - ATTEMPT STOLEN',
       'BATTERY WITH SEXUAL CONTACT', 'DOCUMENT FORGERY / STOLEN FELONY',
       'BATTERY POLICE (SIMPLE)',
       'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT',
       'DISTURBING THE PEACE', 'OTHER ASSAULT',
       'VIOLATION OF RESTRAINING ORDER', 'LEWD CONDUCT',
       'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)',
       'THEFT OF IDENTITY',
       'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER',
       'CHILD ANNOYING (17YRS & UNDER)',
       'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH',
       'ORAL COPULATION', 'CRUELTY TO ANIMALS',
       'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
       'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD', 'PEEPING TOM',
       'INDECENT EXPOSURE', 'BIKE - STOLEN',
       'BURGLARY FROM VEHICLE, ATTEMPTED', 'BURGLARY, ATTEMPTED',
       'STALKING', 'THREATENING PHONE CALLS/LETTERS',
       'SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ',
       'BUNCO, PETTY THEFT', 'BUNCO, GRAND THEFT',
       'VIOLATION OF TEMPORARY RESTRAINING ORDER',
       'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
       'SEXUAL PENETRATION W/FOREIGN OBJECT', 'EXTORTION', 'PICKPOCKET',
       'EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)', 'PURSE SNATCHING',
       'WEAPONS POSSESSION/BOMBING', 'COUNTERFEIT', 'FALSE IMPRISONMENT',
       'CREDIT CARDS, FRAUD USE ($950.01 & OVER)',
       'DISCHARGE FIREARMS/SHOTS FIRED', 'THEFT FROM PERSON - ATTEMPT',
       'UNAUTHORIZED COMPUTER ACCESS', 'PANDERING', 'PIMPING',
       'DRUNK ROLL - ATTEMPT', 'SHOPLIFTING - ATTEMPT',
       'RESISTING ARREST', 'DISHONEST EMPLOYEE - GRAND THEFT',
       'RECKLESS DRIVING', 'PROWLER',
       'CREDIT CARDS, FRAUD USE ($950 & UNDER',
       'DOCUMENT WORTHLESS ($200.01 & OVER)', 'CHILD STEALING',
       'CONTEMPT OF COURT', 'CONSPIRACY',
       'THEFT FROM MOTOR VEHICLE - ATTEMPT', 'DRUNK ROLL',
       'BATTERY ON A FIREFIGHTER', 'ILLEGAL DUMPING', 'LYNCHING',
       'THEFT, COIN MACHINE - PETTY ($950 & UNDER)',
       'GRAND THEFT / INSURANCE FRAUD', 'BUNCO, ATTEMPT',
       'DISRUPT SCHOOL', 'THEFT, COIN MACHINE - GRAND ($950.01 & OVER)',
       'FALSE POLICE REPORT', 'PURSE SNATCHING - ATTEMPT',
       'BOAT - STOLEN',
       'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT',
       'DRIVING WITHOUT OWNER CONSENT (DWOC)', 'CONTRIBUTING',
       'FAILURE TO YIELD', 'TILL TAP - ATTEMPT', 'DRUGS, TO A MINOR',
       'INCITING A RIOT',
       'BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM',
       'BRIBERY', 'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)',
       'DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER',
       'DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01',
       'TILL TAP - GRAND THEFT ($950.01 & OVER)', 'LYNCHING - ATTEMPTED',
       'SEX OFFENDER REGISTRANT OUT OF COMPLIANCE', 'CHILD ABANDONMENT',
       'LEWD/LASCIVIOUS ACTS WITH CHILD',
       'DISHONEST EMPLOYEE - PETTY THEFT', 'TELEPHONE PROPERTY - DAMAGE',
       'PICKPOCKET, ATTEMPT', 'TILL TAP - PETTY ($950 & UNDER)',
       'DOCUMENT WORTHLESS ($200 & UNDER)',
       'HUMAN TRAFFICKING - COMMERCIAL SEX ACTS',
       'MANSLAUGHTER, NEGLIGENT', 'GRAND THEFT / AUTO REPAIR', 'BIGAMY',
       'THEFT, COIN MACHINE - ATTEMPT', 'PETTY THEFT - AUTO REPAIR',
       'BIKE - ATTEMPTED STOLEN', 'FAILURE TO DISPERSE',
       'REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)',
       'HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE', 'CHILD PORNOGRAPHY',
       'ABORTION/ILLEGAL', 'INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)',
       'DISHONEST EMPLOYEE ATTEMPTED THEFT', 'TRAIN WRECKING',
       'BLOCKING DOOR INDUCTION CENTER',
       'FIREARMS RESTRAINING ORDER (FIREARMS RO)',
       'VEHICLE - MOTORIZED SCOOTERS, BICYCLES, AND WHEELCHAIRS',
       'FIREARMS TEMPORARY RESTRAINING ORDER (TEMP FIREARMS RO)'],
      dtype=object)

In [35]:
df.rename(columns={'DATE OCC': 'DATE_OCC'}, inplace=True)

In [36]:
df['DATE_OCC'] = pd.to_datetime(df['DATE_OCC'])

In [37]:
lowest_date = df['DATE_OCC'].min()
highest_date = df['DATE_OCC'].max()

print(f'Lowest date: {lowest_date}')
print(f'Highest date: {highest_date}')

Lowest date: 2010-01-01 00:00:00
Highest date: 2019-12-31 00:00:00

## Importing the Crime_Data_from_2020_to_Present.csv Dataset

In [38]:
df1 = pd.read_csv(project_directory+'/Crime_Data_from_2020_to_Present.csv')

In [39]:
df1

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682330,230806871,03/03/2023 12:00:00 AM,03/02/2023 12:00:00 AM,620,8,West LA,889,2,354,THEFT OF IDENTITY,...,IC,Invest Cont,354.0,NaN,NaN,NaN,2000 S HOLT AV,NaN,34.0412,-118.3814
682331,231104474,01/12/2023 12:00:00 AM,01/12/2023 12:00:00 AM,1240,11,Northeast,1107,1,440,THEFT PLAIN - PETTY ($950 & UNDER),...,IC,Invest Cont,440.0,NaN,NaN,NaN,1000 MILWAUKEE AV,NaN,34.1214,-118.1915
682332,230804266,01/08/2023 12:00:00 AM,01/08/2023 12:00:00 AM,1030,8,West LA,839,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,NaN,NaN,NaN,10200 SANTA MONICA BL,NaN,34.0611,-118.4184
682333,231604807,01/27/2023 12:00:00 AM,01/26/2023 12:00:00 AM,1800,16,Foothill,1663,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,12500 BRANFORD ST,NaN,34.2466,-118.4054
682334,230906458,03/05/2023 12:00:00 AM,03/05/2023 12:00:00 AM,900,9,Van Nuys,914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,NaN,NaN,NaN,14500 HARTLAND ST,NaN,34.1951,-118.4487

In [40]:
df1.nunique()

DR_NO             682335
Date Rptd           1168
DATE OCC            1168
TIME OCC            1439
AREA                  21
AREA NAME             21
Rpt Dist No         1194
Part 1-2               2
Crm Cd               137
Crm Cd Desc          137
Mocodes           233172
Vict Age             102
Vict Sex               4
Vict Descent          19
Premis Cd            309
Premis Desc          306
Weapon Used Cd        79
Weapon Desc           79
Status                 6
Status Desc            6
Crm Cd 1             139
Crm Cd 2             120
Crm Cd 3              35
Crm Cd 4               6
LOCATION           61184
Cross Street        9082
LAT                 5379
LON                 4958
dtype: int64

In [41]:
df1.rename(columns={'Crm Cd Desc': 'Crm_Cd_Desc'}, inplace=True)

In [42]:
df1.rename(columns={'DATE OCC': 'DATE_OCC'}, inplace=True)

In [43]:
df1['DATE_OCC'] = pd.to_datetime(df1['DATE_OCC'])

In [44]:
lowest_date = df1['DATE_OCC'].min()
highest_date = df1['DATE_OCC'].max()

print(f'Lowest date: {lowest_date}')
print(f'Highest date: {highest_date}')

Lowest date: 2020-01-01 00:00:00
Highest date: 2023-03-13 00:00:00